name: JMeter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest
    env:
      JMETER_VERSION: '5.6.3'   # latest stable version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download Apache JMeter
        run: |
          echo "Downloading JMeter version $JMETER_VERSION"
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-${JMETER_VERSION}.tgz
          tar -xzf apache-jmeter-${JMETER_VERSION}.tgz

      - name: Run JMeter Test
        run: |
          rm -rf results-html results.jtl || true
          ./apache-jmeter-${JMETER_VERSION}/bin/jmeter \
            -n -t week4_test.jmx \
            -l results.jtl \
            -e -o results-html
          ls -la results-html || echo "⚠️ No results found!"

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results-html
